CREATE TABLE `feedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `course_id` int DEFAULT NULL,
  `trainer_name` varchar(100) DEFAULT NULL,
  `training_date` date DEFAULT NULL,
  `course_helpful` tinyint(1) DEFAULT NULL,
  `course_rating` int DEFAULT NULL,
  `trainer_rating` int DEFAULT NULL,
  `course_review` text,
  `trainer_review` text,
  `manager_id` int DEFAULT NULL,
  `manager_comments` text,
  `allow_to_continue` enum('yes','no') DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `manager_reviewed` tinyint(1) DEFAULT '0',
  `understood_concepts` text,
  `improvements` text,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `manager_id` (`manager_id`),
  KEY `course_id` (`course_id`),
  CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `feedback_ibfk_2` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`),
  CONSTRAINT `feedback_ibfk_3` FOREIGN KEY (`course_id`) REFERENCES `courses` (`course_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
